In [1]:
import torch

In [2]:
from torch import nn

In [67]:
class PosEncoding(nn.Module):
    def __init__(self, embedding_dim, max_len):
        super(PosEncoding, self).__init__()
        self.pos_enc = torch.zeros(max_len, embedding_dim)

        i_s_divd = torch.arange(0, 2 * embedding_dim, 2) / embedding_dim
        # print(i_s_divd) # OK
        powers = torch.vstack([i_s_divd] * max_len)
        # print(powers) # OK
        divisors = torch.pow(10_000, powers)
        # print(divisors) # OK
        positions = torch.arange(max_len)
        # print(positions) # OK
        positions_mtrx = torch.vstack([positions]*embedding_dim).mT 
        # print(positions_mtrx)
        # self.encoding = positions_mtrx / divisors

        self.encoding = torch.zeros(max_len, embedding_dim)
        self.encoding[:,::2] = torch.sin(positions_mtrx / divisors)[:,::2]
        self.encoding[:,1::2] = torch.cos(positions_mtrx / divisors)[:,1::2].unsqueeze(0)
        print(self.encoding)
        
    def forward(self, x):
        return x + self.encoding[:, :x.shape[0]]
        



In [69]:
pe = PosEncoding(max_len=3, embedding_dim=4)

x = torch.zeros(1,4)

pe(x)

tensor([[0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00],
        [8.4147e-01, 9.9995e-01, 1.0000e-04, 1.0000e+00],
        [9.0930e-01, 9.9980e-01, 2.0000e-04, 1.0000e+00]])


tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.8415, 0.8415, 0.8415, 0.8415],
        [0.9093, 0.9093, 0.9093, 0.9093]])

In [70]:
y = torch.ones(1,4)

pe(y)

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.8415, 1.8415, 1.8415, 1.8415],
        [1.9093, 1.9093, 1.9093, 1.9093]])

In [ ]:
# %pip install zeta

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement zeta (from versions: 0.7b1-py2.6.egg)
ERROR: No matching distribution found for zeta

[notice] A new release of pip is available: 24.0 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip
