In [1]:
import torch

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from torch import nn

In [5]:
from encoder import Encoder
import torch
import torch.nn as nn
from attention import MultiHeadAttention
from feed_forward import FFN
from embedding import Embedding
from pos_en import PosEncoding

In [ ]:
# enc = Encoder(4,2,4,4,1,4)

In [6]:
d_model = 512
num_heads = 8
d_k = d_v = 64
batch_size = 2
seq_len = 10
d_inner = 2048
max_len = 30

Embed = Embedding(max_len, d_model)
tokens = torch.randint(0, 32, (4, max_len))  # give 32 random token indinces (batch of 4, sequence length 100)
embedding = Embed(tokens)

PosEnc = PosEncoding(d_model, max_len)
input = PosEnc(embedding)

# x = torch.randn(batch_size, seq_len, d_model)

encoder = Encoder(d_model, num_heads, d_k, d_v, batch_size, d_inner)

output = encoder(input)

print(output.shape)  # Should be: (2, 10, 512)

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
          0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.6969e-01,  8.0196e-01,  ...,  1.0000e+00,
          1.0746e-08,  1.0000e+00],
        [ 9.0930e-01, -3.5090e-01,  9.5814e-01,  ...,  1.0000e+00,
          2.1492e-08,  1.0000e+00],
        ...,
        [ 9.5638e-01,  6.1128e-01, -7.2968e-03,  ...,  1.0000e+00,
          2.9014e-07,  1.0000e+00],
        [ 2.7091e-01, -3.0219e-01,  7.9758e-01,  ...,  1.0000e+00,
          3.0089e-07,  1.0000e+00],
        [-6.6363e-01, -9.5559e-01,  9.6021e-01,  ...,  1.0000e+00,
          3.1164e-07,  1.0000e+00]])
torch.Size([4, 30, 512])
torch.Size([30, 512])
torch.Size([4, 30, 512])


RuntimeError: The size of tensor a (30) must match the size of tensor b (60) at non-singleton dimension 1

In [69]:
pe = PosEncoding(max_len=3, embedding_dim=4)

x = torch.zeros(1,4)

pe(x)

tensor([[0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00],
        [8.4147e-01, 9.9995e-01, 1.0000e-04, 1.0000e+00],
        [9.0930e-01, 9.9980e-01, 2.0000e-04, 1.0000e+00]])


tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.8415, 0.8415, 0.8415, 0.8415],
        [0.9093, 0.9093, 0.9093, 0.9093]])

In [70]:
y = torch.ones(1,4)

pe(y)

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.8415, 1.8415, 1.8415, 1.8415],
        [1.9093, 1.9093, 1.9093, 1.9093]])

In [ ]:
# %pip install zeta

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement zeta (from versions: 0.7b1-py2.6.egg)
ERROR: No matching distribution found for zeta

[notice] A new release of pip is available: 24.0 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip
